## OpenCV
**Opencv is a open source computer vision image processing library create by intel and later supported by willow garge and now maintaing by ltseez**

**It is easy to use as well as install**

### Install openCV

In [1]:
!pip install opencv-python

In [1]:
# import opencv
import cv2

In [3]:
# Version on openCV
print(cv2.__version__)

4.6.0


**What Is Image & Types Of Image**

In [ ]:
""" Image a collection of Pixels to reprsent the perception of visual's

Two Types Of Images: 
1. GreyScale Image: In grey scale image 1 channel is present, and the range of pixel is 0 to 255
0 represent the black & 1 represent the white

2.RGB Image: In RGB image total 3000 channels are present, 0 represent the balck & 255 represent the red, green & Blue """

### Read Image

In [4]:
img = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\image.jpeg",1)
print(img)

# 1 is used for color image
# 0 is used for grey scal image
# -1 is used for include alpha channe

[[[245 243 243]
  [245 243 243]
  [245 243 243]
  ...
  [186 172 154]
  [185 171 153]
  [184 170 152]]

 [[245 243 243]
  [245 243 243]
  [245 243 243]
  ...
  [193 179 161]
  [191 177 159]
  [190 176 158]]

 [[246 244 244]
  [246 244 244]
  [245 243 243]
  ...
  [201 186 170]
  [200 185 169]
  [199 184 168]]

 ...

 [[236 226 216]
  [238 228 218]
  [240 230 220]
  ...
  [187 186 202]
  [187 186 202]
  [187 186 202]]

 [[241 236 233]
  [241 236 233]
  [242 237 234]
  ...
  [186 183 198]
  [186 183 198]
  [186 183 198]]

 [[239 237 237]
  [238 236 236]
  [238 236 236]
  ...
  [184 181 196]
  [184 181 196]
  [185 182 197]]]


* Image read in the form of array

### Display the read image

In [6]:
cv2.imshow('image',img)
cv2.waitKey(0) & 0xff  
# 0 is used to hold the image
# & 0xff is used beacuse of 64bit operating system

255

### Write Image

In [9]:
cv2.imwrite('new_image.jpg',img)  #Save previous image
# 1st argument is name of new image
# 2nd argument is path of image as well as veriable of reading image

True

### Save the image

In [11]:
image = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\anarchy-anonymous-computer-hack-wallpaper-preview.jpg")  
cv2.imshow('img', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [1]:
import cv2

In [6]:
img = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\pandasecurity-How-do-hackers-pick-their-targets.jpg",1)
cv2.imshow("Hacker",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
cv2.imwrite('hacker.png',img)

True

**Convert Image RGB Image Into GreyScale**

In [3]:
img = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\multiple-objects-any-kind-designing-260nw-2194193801.webp")

# Convert image into Greyscale.
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) 
""" 1st Parameter is for image veriable &
2nd parameter for convert image into grey scale"""

cv2.imshow('Hacker', img_gray)
cv2.waitKey()


13

In [5]:
# Shape of image
img_gray.shape # No of channel is not coming becuase of gray scale image

(280, 260)

**Operations With RGB Images**

**Hide Blue Channel From RGB Image**

In [7]:
img = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\multiple-objects-any-kind-designing-260nw-2194193801.webp")

img[:,:,0] = 0  # Hide blue Channel

cv2.imshow('Image',img)
cv2.waitKey()
cv2.destroyAllWindows()

**Hide Green Channel From RGB Image**

In [16]:
img = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\multiple-objects-any-kind-designing-260nw-2194193801.webp")

img[:,:,1] = 0  # Hide green channel Channel

cv2.imshow('Image',img)
cv2.waitKey()
cv2.destroyAllWindows()

**Hide Red Channel From RGB Image**

In [18]:
img = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\multiple-objects-any-kind-designing-260nw-2194193801.webp")

img[:,:,2] = 0 # Hide blue Channel

cv2.imshow('Image',img_red)
cv2.waitKey()
cv2.destroyAllWindows()

**Seprate The All channel And Visualise at same time**

In [24]:
import numpy as np

img = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\multiple-objects-any-kind-designing-260nw-2194193801.webp")

img_blue  = img[:,:,0] # Blue
img_green = img[:,:,1] # Green
img_red   = img[:,:,2] # Red

new_image = np.hstack((img_blue,img_green, img_red)) # Used to visu

cv2.imshow('Image',new_image)
cv2.waitKey()
cv2.destroyAllWindows()

**Resize The Image**

In [4]:
img = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\multiple-objects-any-kind-designing-260nw-2194193801.webp")

img_resize = cv2.resize(img, (256,256)) # Resize the image

cv2.imshow('Image',img_resize)
cv2.waitKey()
cv2.destroyAllWindows()

print(img.shape)

(280, 260, 3)


**Flipping The Image**

In [5]:
img = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\multiple-objects-any-kind-designing-260nw-2194193801.webp")

img_flip = cv2.flip(img, 0)

""" 0 is used to flip the image on vertical axis
1 is used to flip the image on Horizontal axis
-1 is used to flip the image on both vertical & horizontal axis"""

cv2.imshow("Image", img_flip)
cv2.waitKey()
cv2.destroyAllWindows()

**Cropping The Image**

In [8]:
img = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\multiple-objects-any-kind-designing-260nw-2194193801.webp")

img_crop = img[50:300, 100:200]  # Here we will be used slicing for crop the image 1st for height & 2nd used for width

cv2.imshow('Image', img_crop)
cv2.waitKey()
cv2.destroyAllWindows()

**Save The Image**

In [9]:
img = cv2.imread(r"C:\Users\hp\OneDrive\Pictures\multiple-objects-any-kind-designing-260nw-2194193801.webp")

img_crop = img[0:300,0:200]

cv2.imwrite('fruit_save.png',img_crop)

True

**Drawing Shapes & Text Over The Images**

In [7]:
""" Create a New Image and
draw the shape over the image"""

import numpy as np
import cv2



In [9]:
# Create a white image
img = np.ones((256,256,3))  

cv2.imshow('Image',img)

cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
# Create a black image
img = np.zeros((256,256,3))  

cv2.imshow('Image',img)

cv2.waitKey()
cv2.destroyAllWindows()

**Drawing Rectangle Over The Image**

In [8]:
# Create a ractangel
img = np.zeros((512,512,3))  

""" 1st parameter for image,
2nd & 3rd parameter for point of ractangle,
4th parameter for color & 5th parameter for thickness """

cv2.rectangle(img, pt1=(50,50), pt2=(200,200), color=(256,0,0), thickness=3) # If you want to fill the whole image with color used -1

cv2.imshow('Image',img)

cv2.waitKey()
cv2.destroyAllWindows()

**Drawing Circle Over The Image**

In [6]:
# Create a circle
img = np.zeros((512,512,3))  

""" 1st parameter for image,
2nd parameter for center of the circle, 4th parameter for radius of the circle,
4th parameter for color & 5th parameter for thickness """

cv2.circle(img,center=(100,200),radius=100,color=(0,256,0), thickness=3)

cv2.imshow('Image',img)

cv2.waitKey()
cv2.destroyAllWindows()

**Drawing Line Over The Image**

In [4]:
import cv2
import numpy as np

In [5]:
# draw line
img = np.zeros((512,512,3))  

""" 1st parameter for image,
2nd & 3rd parameter for point of line,
4th parameter for color & 5th parameter for thickness """

cv2.line(img, pt1=(10,10), pt2=(500,10), color=(0,256,0), thickness=3)

cv2.imshow('Image',img)

cv2.waitKey()
cv2.destroyAllWindows()

**Write Text Over The Image**

In [7]:
# Text writing 
img = np.zeros((512,512,3))  

""" 1st parameter for image,
2nd paramter for stating point of text
3rd parameter for font size,
4th parameter for color & 5th parameter for thickness
6th parameter for fontface (Which font you want to use),
6th parameter for text"""

cv2.putText(img,org=(0,200),fontScale=5,text="IMAGE",fontFace=cv2.FONT_HERSHEY_COMPLEX,color=(256,0,0), thickness=3)

cv2.imshow('Image',img)

cv2.waitKey()
cv2.destroyAllWindows()